
export const AUTH = 'AUTHENTICATE';
export const UNAUTH = 'UNAUTHORIZED';
export const CREATEUSER = 'CREATEUSER'
export const SAVETOKEN = 'SAVETOKEN';

export const SEARCHBOOK = 'SEARCHBOOK';
export const RECEIVEBOOK = 'RECEIVEBOOK';
export const SENDSTORAGE = 'SENDSTORAGE';
export const REQUESTALLBOOKDATA = 'REQUESTALLBOOKDATA';
export const GETBOOKSFROMDB = 'GETBOOKSFROMDB';
